#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

if [ -e /usr/share/exodus/exodus-installer ]
then
	/usr/share/exodus/exodus-installer uninstall
fi

#DEBHELPER#

# vim: ts=4 sw=4 et
